type = "cron"
schemaVersion = 1
name = "[CRON] GET > Uint256"
externalJobID = "07358eac-2ee3-4304-b764-881bae899c4d"
forwardingAllowed = false
maxTaskDuration = "0s"
schedule = "CRON_TZ=UTC @every 1m"
observationSource = """
fetch          [type="http" method="GET" url="https://e28f-160-202-37-181.ngrok-free.app"]
parse          [type="jsonparse" path="balance" data="$(fetch)"]
multiply       [type="multiply" input="$(parse)" times="100"]
encode_data  [type="ethabiencode" abi="(uint256 value)" data="{ \\"value\\": $(multiply) }"]
encode_tx      [type="ethabiencode"
                abi="fulfillMultipleParameters2(bytes32 reserveResponse)"
                data="{ \\"reserveResponse\\": $(encode_data) }"]
submit_tx      [type="ethtx" to="0x1757b514ED636566FE50176D91372C74cAE68665" data="$(encode_tx)" evmChainID="4002"]

fetch -> parse -> multiply -> encode_data -> encode_tx -> submit_tx
"""
