type = "cron"
schemaVersion = 1
name = "[CRON] GET > Uint256"
externalJobID = "180efcb2-edec-482f-8f7c-8f1386b37265"
forwardingAllowed = false
maxTaskDuration = "0s"
schedule = "CRON_TZ=UTC @every 1m"
observationSource = """
fetch          [type="http" method="GET" url="http://localhost:3000/"]
parse           [type="jsonparse" path="balance" data="$(fetch)"]
multiply       [type="multiply" input="$(parse)" times="100"]
encode_data  [type="ethabiencode" abi="(uint256 value)" data="{ \\"value\\": $(multiply) }"]
encode_tx      [type="ethabiencode" 
                abi="requestMultipleParameters()" 
                data="{}"]
submit_tx      [type="ethtx" to="0xb19f7717BE51937E69CC22b721511da76643DE72" data="$(encode_tx)" evmChainID="4002"]

fetch -> parse -> multiply -> encode_data -> encode_tx -> submit_tx
"""